services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: protube
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./docker-postgres:/var/lib/postgresql/data
    restart: always
