services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: protube
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/pgdata
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - ./docker-postgres:/var/lib/postgresql/data
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: protube
    volumes:
      - ./docker-mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
